### PR TITLE
Retry when connecting fails

### PR DESCRIPTION
**Pull request by Bond-009**
Keep trying to connect, waiting 15sec between failed attempts

### CODE REVIEW

**Review by jewlexx — CHANGES_REQUESTED** [review]
time import should be one line, i.e

```rust
time::{self, Duration}
```

**Comment by jewlexx** [comment]
I'll do some testing and see how this works, thank you for the PR

**Review by jewlexx — APPROVED** [review]

**Comment by jewlexx** [comment]
Everything seems to work fine, the only issue I have is why implement this in the library itself? I feel asthough it would be a better idea to leave it up to the developers to implement it or add customization.

**Comment by Bond-009** [comment]
It worked like this in the original lib you forked. Not sure why the user of the lib should be concerned about the internal connection.

**Comment by jewlexx** [comment]
> Not sure why the user of the lib should be concerned about the internal connection.

Because they may want the RPC to simply exit if it fails. If they wish for it to retry continually, then they can implement that themselves otherwise we can add a flag, or seperate function to initialize it, and retry upon failure.

**Pull request closed without merging**
