### PR TITLE
Support for different activity types

### PR DESCRIPTION
**Pull request by natawie**
Allows setting different activity types (e.g. "Listening to…", "Watching…")(#97)

Not [all activity types](https://discord.com/developers/docs/game-sdk/activities#data-models-activitytype-enum) are accepted when trying to set them, Streaming and Custom cause an error, so I left them out.

Although (I think) undocumented, it does work.
"Listening to mpddrp-rs"
"Competing in mpddrp-rs"

### CODE REVIEW

**Comment by jewlexx** [comment]
I'm a little hesitant about merging this because the docs specifically say "a payload with an ActivityType sent ... will be discarded and will not change anything in the client".

If I do merge I need it to be clear this is not supported by Discord and may break in the future without warning.

**Comment by natawie** [comment]
I think that part in the docs refers specifically to the Game SDK discarding it, seeing how they could (and with that phrasing, should) just ignore it in the app.

But of course I'm willing to add whatever you think would be best.
I thought of three options:
* a feature flag
* a warning with `#[deprecated()]`
* a disclaimer in the docs

**Comment by jewlexx** [comment]
According to [this Tweet](https://x.com/advaithj1/status/1816655583107510517) it seems like this feature has been intentionally enabled, but still very recently, and could be rolled back, or cause issues with people on older versions of Discord. So I think locking it behind a feature flag would be best for now, and maybe enable it by default in future.

I'll also look into supporting `Streaming` and `Custom`, because they should work, [they just require additional fields](https://discord.com/developers/docs/topics/gateway-events#activity-object-activity-types).

**Comment by natawie** [comment]
`Streaming` or `Custom` don't appear to be supported at all currently. This is what is returned by Discord:
`{"cmd":"SET_ACTIVITY","data":{"code":4000,"message":"child \\"activity\\" fails because [child \\"type\\" fails because [\\"type\\" must be one of [0, 2, 3, 5]]]"},"evt":"ERROR","nonce":"..."}`

**Comment by jewlexx** [comment]
I've added a little helper to the macros, so you should be able to just add `if feature = "<feature name>"` before the comma on the `_type` field.

If you could add the feature flag and that specifier that would be great.

**Comment by jewlexx** [comment]
Thanks for your work in this

**Pull request merged**
